Fix getUserMedia arguments error
Fix `getUserMedia` arguments error

```
TypeError: Failed to execute 'webkitGetUserMedia' on 'Navigator': 3
arguments required, but only 2 present.
```

Add error handler for `scope.disableCamera` in the same way as it was
done for `scope.enableCamera`